from __future__ import annotations

import sys
import subprocess
from io import BytesIO
from datetime import datetime
from typing import Any

import streamlit as st

from utils.state_utils import APP_NAME, APP_VERSION, PALETTE, t
from recommendations import products_for, recommendation_profile


def ensure_reportlab():
    try:
        import reportlab
        return reportlab
    except ImportError:
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "reportlab", "-q"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            import reportlab
            return reportlab
        except Exception:
            return None


def build_pdf_report(result: dict[str, Any]) -> bytes:
    reportlab = ensure_reportlab()
    if reportlab is None:
        raise RuntimeError("PDF generation unavailable. Please install reportlab.")
    
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=42, leftMargin=42, topMargin=42, bottomMargin=42)
    styles = getSampleStyleSheet()
    
    skin = result["skin"]
    profile = result["profile"]
    rec = recommendation_profile(skin)
    products = products_for(skin)
    translated_skin = t(skin)
    
    story = [
        Paragraph(f"<b>{APP_NAME}</b>", styles["Title"]),
        Paragraph(t("AI Powered Skin Analysis Report"), styles["Heading2"]),
        Spacer(1, 14),
    ]
    
    story.extend(section_table(t("Patient Summary"), [
        [t("Date"), result["timestamp"].strftime("%d %b %Y"), t("Prediction ID"), result["prediction_id"]],
        [t("Skin Type"), translated_skin, t("Confidence"), f"{result['confidence']}%"],
        [t("Health Score"), f"{result['health_score']}/100", t("Model"), result["model"]],
        [t("Provider"), t(str(result["device"])), t("Inference Time"), f"{result['inference_ms']} ms"]
    ]))
    
    story.extend(section_table(t("Skin Analysis"), [
        [t("Oil Level"), t(profile["oil"])],
        [t("Hydration Level"), t(profile["hydration"])],
        [t("Sensitivity"), t(profile["sensitivity"])],
        [t("Severity"), t(result["severity"])],
        [t("Concerns"), ", ".join(t(item) for item in result["concerns"])],
        [t("AI Explanation"), t(profile["explanation"])]
    ]))
    
    story.extend(section_table(t("Recommendations"), [
        [t("Morning"), " > ".join(t(item) for item in rec["morning"])],
        [t("Night"), " > ".join(t(item) for item in rec["night"])],
        [t("Weekly"), " > ".join(t(item) for item in rec["weekly"])],
        [t("Use"), ", ".join(t(item) for item in rec["use"])],
        [t("Avoid"), ", ".join(t(item) for item in rec["avoid"])],
        [t("Lifestyle"), ", ".join(t(item) for item in rec["lifestyle"])],
        [t("Dermatologist Advice"), t(rec["advice"])]
    ]))
    
    product_rows = []
    for p in products[:10]:
        benefits = t(p["benefits"])
        usage = t(p["usage"])
        if benefits == p["benefits"]:
            benefits = t("Supports your skin routine")
        if usage == p["usage"]:
            usage = t("Use as directed")
        product_rows.append([t(p["category"]), f"{p['name']} - {benefits} ({usage})"])
    story.extend(section_table(t("Products"), product_rows))
    
    story.extend(section_table(t("Risk Assessment"), [
        [f"{t(name)} {t('Risk')}", t(level)] for name, level in profile["risks"].items()
    ]))
    
    story.append(Paragraph(f"<b>{t('Medical Disclaimer')}</b>", styles["Heading2"]))
    story.append(Paragraph(t("This AI-generated report is for informational purposes only and is not a medical diagnosis or a substitute for consultation with a licensed dermatologist."), styles["BodyText"]))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"{t('Generated by')} {APP_NAME} v{APP_VERSION} {t('on')} {datetime.now().strftime('%d %b %Y, %I:%M %p')}", styles["Italic"]))
    
    doc.build(story)
    return buffer.getvalue()


def section_table(title: str, rows: list) -> list:
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, Spacer, Table, TableStyle

    styles = getSampleStyleSheet()
    data = [[Paragraph(f"<b>{title}</b>", styles["Heading2"]), "", "", ""]] + rows
    table = Table(data, colWidths=[115, 125, 115, 125])
    table.setStyle(TableStyle([
        ("SPAN", (0, 0), (-1, 0)),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(PALETTE["primary"])),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), .35, colors.HexColor("#E5E7EB")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7F8FF")]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7)
    ]))
    return [Spacer(1, 10), table, Spacer(1, 12)]
